export interface Client {
  id?: number;
  apiKey?: string; // Optional: not returned by backend after V8 migration (hashed internally)
  name: string;
  priority: number;
  active: boolean;
  authMethod?: 'HMAC'; // Authentication method (HMAC only, legacy removed)
  status?: 'ACTIVE' | 'SUSPENDED' | 'REVOKED'; // Client status
  createdAt?: string;
}

/**
 * Response from create/update client operations.
 * Includes API key in plain text ONLY when it's been created or updated.
 * This is the ONLY time the API key will be visible.
 */
export interface ClientResponse {
  id: number;
  apiKey?: string; // Present only when created/updated with new API key
  apiSecret?: string; // Present only when created (HMAC authentication)
  name: string;
  priority: number;
  active: boolean;
  authMethod?: 'HMAC';
  status?: 'ACTIVE' | 'SUSPENDED' | 'REVOKED';
  createdAt?: string;
  warning?: string; // Warning message about API key/secret visibility
}

export interface ApiSecretResponse {
  clientId: number;
  apiSecret: string;
  message: string;
  warning: string;
}
export interface ClientLimit {
  id?: number;
  clientId: number;
  windowSizeSeconds: number;
  maxRequestsPerWindow: number;
  monthlyQuota: number;
  softThrottleThreshold?: number;
  hardRejectThreshold?: number;
  createdAt?: string;
}
export interface CreateClientRequest {
  apiKey?: string; // Optional - will be auto-generated by backend if not provided
  name: string;
  priority?: number;
  active?: boolean;
}
export interface UpdateClientRequest {
  apiKey?: string;
  name?: string;
  priority?: number;
  active?: boolean;
}
export interface ClientLimitRequest {
  windowSizeSeconds: number;
  maxRequestsPerWindow: number;
  monthlyQuota: number;
  softThrottleThreshold?: number;
  hardRejectThreshold?: number;
}
export interface WindowUsage {
  currentCount: number;
  maxRequests: number;
  windowSizeSeconds: number;
  usagePercent: number;
  remaining: number;
  resetTime: string;
  isSoftThrottled: boolean;
  isBlocked: boolean;
}
export interface MonthlyUsage {
  currentCount: number;
  monthlyQuota: number;
  usagePercent: number;
  remaining: number;
  isSoftThrottled: boolean;
  isBlocked: boolean;
}
export interface ClientStatus {
  isActive: boolean;
  isBlocked: boolean;
  isSoftThrottled: boolean;
  statusMessage: string;
  nextReset: string | null;
}
export interface ClientDetailsResponse {
  client: Client;
  limit: ClientLimit | null;
  windowUsage: WindowUsage | null;
  monthlyUsage: MonthlyUsage | null;
  status: ClientStatus;
}
export interface SystemLimit {
  id?: number;
  name: string;
  windowSizeSeconds: number;
  maxRequestsPerWindow: number;
  active: boolean;
  createdAt?: string;
}
export interface SystemLimitRequest {
  name: string;
  windowSizeSeconds: number;
  maxRequestsPerWindow: number;
  active?: boolean;
}
