spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notifications
    username: postgres
    password: postgres

  data:
    redis:
      host: redis
      port: 6379

app:
  crypto:
    master-key: ${APP_CRYPTO_MASTER_KEY:}
