spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379

admin:
  username: admin
  password: admin123

cache:
  type: caffeine

cors:
  allowed-origins: "http://localhost,http://localhost:1015,http://localhost:1315,http://localhost:4200,http://localhost:8080"
